title                   : jhosler
name                    : Jack Hosler

# Site Author
author:
  name                  : "Jack Hosler"
  avatar                : /assets/images/bio-photo.jpg
  bio                   : ""
  location              : "Huntingdon PA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "jhosler02@gmail.com"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jackhosler/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jhosler02"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jhosler02"
  since: "2025"


baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jhosler02

# Build settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
enable_darkmode: true
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
